---
- name: Create fasd directory
  file:
    path: /home/vagrant/fasd-{{fasd_version}}
    state: directory

- name: Unarchive fasd
  unarchive:
    src: https://github.com/clvv/fasd/tarball/{{fasd_version}}
    remote_src: yes
    dest: /home/vagrant/fasd-{{fasd_version}}
    creates: /home/vagrant/ranger-{{fasd_version}}

- name: install fasd
  command: make install
  args:
    chdir: /home/vagrant/fasd-{{fasd_version}}
    creates: /bin/fasd
