---
- name: link dotfiles
  become: vagrant
  file:
    state: link
    src: /home/vagrant/.dotfiles/{{ item }}
    dest: /home/vagrant/{{ item }}
  with_items:
    - .tmux.conf

- name: Uninstall stuff
  yum:
    name: "{{item}}"
    state: absent
  with_items:
    - tmux

- name: Download tmux
  get_url:
    url: https://github.com/tmux/tmux/releases/download/{{tmux_version}}/tmux-{{tmux_version}}.tar.gz
    dest: /tmp/tmux-{{tmux_version}}.tar.gz

- name: unarchive tmux
  unarchive:
    src: /tmp/tmux-{{tmux_version}}.tar.gz
    dest: /tmp
    creates: /tmp/tmux-{{tmux_version}}

- name: configure tmux
  command: ./configure --prefix=/usr/local
  args:
    chdir: /tmp/tmux-{{tmux_version}}
    creates: /tmp/tmux-{{tmux_version}}/Makefile

- name: compile tmux
  command: make
  args:
    chdir: /tmp/tmux-{{tmux_version}}
    creates: /tmp/tmux-{{tmux_version}}/tmux

- name: install tmux
  command: make install
  args:
    chdir: /tmp/tmux-{{tmux_version}}
    creates: /usr/local/bin/tmux

- name: Make .tmux/plugins
  become: vagrant
  file: state=directory path=/home/vagrant/.tmux/plugins

- name: Install tpm
  become: vagrant
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: /home/vagrant/.tmux/plugins/tpm
    version: master

- name: Install tmp plugins
  become: vagrant
  command: /home/vagrant/.tmux/plugins/tpm/bin/install_plugins
  args:
    creates: /home/vagrant/.tmux/plugins/tmux-sensible
