---
- name: link dotfiles
  become: vagrant
  file:
    state: link
    src: /home/vagrant/.dotfiles/{{ item }}
    dest: /home/vagrant/{{ item }}
  with_items:
    - .vimrc

- name: Uninstall stuff
  yum:
    name: "{{item}}"
    state: absent
  with_items:
    - vim

- name: clone vim
  git:
    repo: https://github.com/vim/vim.git
    dest: /tmp/vim
    version: master

- name: compile vim
  command: make
  args:
    chdir: /tmp/vim/src
    creates: /tmp/vim/src/vim

- name: install vim
  command: make install
  args:
    chdir: /tmp/vim/src
    creates: /usr/local/bin/vim

- name: Make .vim/autoload
  become: vagrant
  file:
    state: directory
    path: /home/vagrant/.vim/autoload

- name: Install vim-plug
  become: vagrant
  get_url:
    dest: /home/vagrant/.vim/autoload/plug.vim
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

- name: Install vim plugins
  become: vagrant
  shell: echo | echo | vim +PlugInstall +qall &> /dev/null
  args:
    creates:
      /home/vagrant/.vim/bundle
